name: github-daily-top

on:
  workflow_dispatch:
  schedule:
    - cron: "1 0 * * *"

jobs:
  fetch-top-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: npm install
        run: npm install --only=prod
        working-directory: .
      - name: fetch
        run: node index.js
        working-directory: .
        # for github app auth
        env:
          clientSecret: ${{ secrets.clientSecret }}
          privateKey: ${{ secrets.privateKey }}

