name: github-daily-top

on:
  workflow_dispatch:
  schedule:
    - cron: "1 0 * * *"

jobs:
  fetch-top-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: nanasess/setup-chromedriver@v1
#        with:
#          # Optional: do not specify to match Chrome's version
#          chromedriver-version: '88.0.4324.96'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: npm install
        run: npm install --only=prod
        working-directory: .
      - name: fetch
        run: node index.js
        working-directory: .
        # for github app auth
        env:
          clientSecret: ${{ secrets.clientSecret }}
          privateKey: ${{ secrets.privateKey }}

